# Generated by Django 4.2.27 on 2025-12-29 16:12

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_ltv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_dbr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bank_products',
                'ordering': ['bank_name', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('incubation', 'Incubation'), ('live', 'Live'), ('pause', 'Pause')], default='incubation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=10, unique=True)),
                ('case_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], max_length=20)),
                ('service_type', models.CharField(choices=[('assisted', 'Assisted'), ('fullyPackaged', 'Fully Packaged')], max_length=20)),
                ('application_type', models.CharField(choices=[('individual', 'Individual'), ('joint', 'Joint')], max_length=20)),
                ('mortgage_type', models.CharField(choices=[('islamic', 'Islamic'), ('conventional', 'Conventional')], max_length=20)),
                ('emirate', models.CharField(choices=[('abuDhabi', 'Abu Dhabi'), ('ajman', 'Ajman'), ('dubai', 'Dubai'), ('fujairah', 'Fujairah'), ('rak', 'Ras Al Khaimah'), ('sharjah', 'Sharjah'), ('uaq', 'Umm Al Quwain')], max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('primaryPurchase', 'Primary Purchase'), ('resale', 'Resale'), ('buyoutEquity', 'Buyout + Equity'), ('buyout', 'Buyout'), ('equity', 'Equity')], max_length=20)),
                ('mortgage_term_years', models.PositiveIntegerField()),
                ('mortgage_term_months', models.PositiveIntegerField(default=0)),
                ('estimated_property_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_status', models.CharField(choices=[('ready', 'Ready'), ('underConstruction', 'Under Construction')], max_length=20)),
                ('stage', models.CharField(choices=[('processing', 'Processing'), ('submitted', 'Submitted'), ('underReview', 'Under Review'), ('preApproved', 'Pre-Approved'), ('valuation', 'Valuation'), ('folProcessing', 'FOL Processing'), ('folReceived', 'FOL Received'), ('folSigned', 'FOL Signed'), ('disbursed', 'Disbursed'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='processing', max_length=20)),
                ('stage_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_products', models.ManyToManyField(related_name='cases', to='core.bankproduct')),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('residency_status', models.CharField(choices=[('citizen', 'Citizen'), ('resident', 'Resident')], default='resident', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('selfEmployed', 'Self Employed')], default='employed', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_property_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eligibility_status', models.CharField(choices=[('pending', 'Pending'), ('eligible', 'Eligible'), ('notEligible', 'Not Eligible')], default='pending', max_length=20)),
                ('estimated_dbr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estimated_ltv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_channel', models.CharField(choices=[('Meta', 'Meta'), ('Google', 'Google'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('AskRivo', 'AskRivo'), ('PartnerDSA', 'Partner DSA'), ('RMA', 'RMA')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('notProceeding', 'Not Proceeding'), ('notEligible', 'Not Eligible')], default='active', max_length=20)),
                ('status_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('channel', models.CharField(choices=[('Meta', 'Meta'), ('Google', 'Google'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('AskRivo', 'AskRivo')], max_length=20)),
                ('intent', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('dropped', 'Dropped'), ('converted', 'Converted')], default='new', max_length=20)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.campaign')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('case', 'Case')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='notes_entity__fbdd3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('converted_to_client', 'Converted to Client'), ('dropped', 'Dropped')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.lead')),
            ],
            options={
                'db_table': 'lead_status_changes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClientStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('converted_to_case', 'Converted to Case'), ('not_eligible', 'Not Eligible'), ('not_proceeding', 'Not Proceeding')], max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='core.client')),
            ],
            options={
                'db_table': 'client_status_changes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='converted_from_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_client', to='core.lead'),
        ),
        migrations.AddField(
            model_name='client',
            name='eligible_bank_products',
            field=models.ManyToManyField(blank=True, related_name='eligible_clients', to='core.bankproduct'),
        ),
        migrations.AddField(
            model_name='client',
            name='source_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.campaign'),
        ),
        migrations.CreateModel(
            name='CaseStageChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(blank=True, max_length=20, null=True)),
                ('to_stage', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_changes', to='core.case')),
            ],
            options={
                'db_table': 'case_stage_changes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='core.client'),
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('client', 'Client'), ('case', 'Case')], max_length=20)),
                ('entity_id', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('connected', 'Connected'), ('noAnswer', 'No Answer'), ('busy', 'Busy'), ('wrongNumber', 'Wrong Number'), ('switchedOff', 'Switched Off')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='call_logs_entity__6b56af_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('passport', 'Passport'), ('emiratesId', 'Emirates ID'), ('visa', 'Visa'), ('salaryCertificate', 'Salary Certificate'), ('payslips', 'Payslips'), ('bankStatements', 'Bank Statements'), ('creditCardStatement', 'Credit Card Statement'), ('loanStatements', 'Loan Statements')], max_length=30)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('notApplicable', 'Not Applicable')], default='missing', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.client')),
            ],
            options={
                'db_table': 'documents',
                'unique_together': {('client', 'type')},
            },
        ),
        migrations.CreateModel(
            name='BankForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('accountOpeningForm', 'Account Opening Form'), ('fts', 'FTS'), ('kfs', 'KFS'), ('undertakings', 'Undertakings'), ('bankChecklist', 'Bank Checklist')], max_length=30)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('uploaded', 'Uploaded'), ('verified', 'Verified')], default='missing', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_forms', to='core.case')),
            ],
            options={
                'db_table': 'bank_forms',
                'unique_together': {('case', 'type')},
            },
        ),
    ]
