# Generated by Django 4.2.27 on 2025-12-31 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='status',
        ),
        migrations.AddField(
            model_name='channel',
            name='default_sla_min',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='channel',
            name='trust_level',
            field=models.CharField(choices=[('trusted', 'Trusted'), ('untrusted', 'Untrusted')], default='trusted', max_length=10),
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.CharField(choices=[('perf_marketing', 'Performance Marketing'), ('partner_hub', 'Partner Hub'), ('freelance', 'Freelance Network'), ('bh_mortgage', 'BH Mortgage Team'), ('askrivo', 'AskRivo')], max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='channel',
            table='channel',
        ),
        migrations.CreateModel(
            name='SubSource',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_sources', to='core.source')),
            ],
            options={
                'db_table': 'sub_source',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='source',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.channel'),
        ),
    ]
