# Generated by Django 4.2.27 on 2025-12-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_source_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subsource',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subsource',
            name='status',
            field=models.CharField(choices=[('incubation', 'Incubation'), ('live', 'Live'), ('paused', 'Paused'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
