# Generated by Django 4.2.27 on 2025-12-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_source_is_active_remove_subsource_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='default_sla_min',
        ),
        migrations.AddField(
            model_name='subsource',
            name='default_sla_min',
            field=models.IntegerField(default=30),
        ),
    ]
