# Generated by Django 4.2.27 on 2025-12-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_channel_default_sla_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsource',
            name='default_sla_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
