# Generated by Django 4.2.27 on 2025-12-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_systemsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankproduct',
            options={'ordering': ['bank_name', 'type_of_mortgage']},
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='max_dbr',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='max_ltv',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='bankproduct',
            name='rate',
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='bank_icon',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='bank_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='buyout_processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='citizen_state',
            field=models.CharField(choices=[('UAE RESIDENT', 'UAE Resident'), ('UAE NATIONAL', 'UAE National'), ('NON RESIDENT', 'Non Resident'), ('ALL', 'All')], default='UAE RESIDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='customer_segments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='early_settlement_fee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='eibor_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='eibor_type',
            field=models.CharField(choices=[('EIBOR 3 MONTH', 'EIBOR 3 Month'), ('EIBOR 6 MONTH', 'EIBOR 6 Month'), ('EIBOR 1 YEAR', 'EIBOR 1 Year')], default='EIBOR 3 MONTH', max_length=20),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='fixed_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='fixed_until',
            field=models.IntegerField(default=0, help_text='Fixed rate period in years'),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='follow_on_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='follow_on_rate_type',
            field=models.CharField(choices=[('variable_addition', 'Variable Addition'), ('fixed', 'Fixed')], default='variable_addition', max_length=20),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='has_fee_financing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='home_valuation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='includes_agency_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='includes_government_fees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='interest_rate_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='variable', max_length=10),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='life_insurance',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Life insurance rate as percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='life_insurance_payment_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually'), ('one_time', 'One Time')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='loan_to_value_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='loan_to_value_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='maximum_length_of_mortgage',
            field=models.IntegerField(default=25, help_text='Maximum mortgage term in years'),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='minimum_mortgage_processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='minimum_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='mortgage_contract_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='mortgage_processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='As percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='mortgage_processing_fee_as_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='overpayment_fee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='pre_approval_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='property_insurance',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Property insurance rate as percentage', max_digits=6),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='property_insurance_payment_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually'), ('one_time', 'One Time')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='type_of_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='type_of_employment',
            field=models.CharField(choices=[('SALARIED', 'Salaried'), ('SELF EMPLOYMENT', 'Self Employed'), ('ALL', 'All')], default='SALARIED', max_length=30),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='type_of_mortgage',
            field=models.CharField(choices=[('ISLAMIC', 'Islamic'), ('CONVENTIONAL', 'Conventional')], default='CONVENTIONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='type_of_transaction',
            field=models.CharField(choices=[('PRIMARY PURCHASE', 'Primary Purchase'), ('RESALE', 'Resale'), ('HANDOVER', 'Handover'), ('PRIMARY/RESALE/HANDOVER', 'Primary/Resale/Handover'), ('BUYOUT', 'Buyout'), ('EQUITY RELEASE', 'Equity Release')], default='PRIMARY PURCHASE', max_length=50),
        ),
        migrations.AddField(
            model_name='bankproduct',
            name='variable_rate_addition',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='EiborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('overnight', 'Overnight'), ('1_week', '1 Week'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('1_year', '1 Year')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'eibor_rates',
                'ordering': ['-date', 'term'],
                'unique_together': {('term', 'date')},
            },
        ),
    ]
