# Generated by Django 4.2.27 on 2025-12-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bank_products_extended'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['stage'], name='cases_stage_c6963e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-created_at'], name='cases_created_59494d_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='clients_status_98ee60_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['eligibility_status'], name='clients_eligibi_ca1956_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['source_channel'], name='clients_source__9ad47c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['-created_at'], name='clients_created_cf1920_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_status_94f025_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['channel'], name='leads_channel_3d83b7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['-created_at'], name='leads_created_f50ac1_idx'),
        ),
    ]
