# Generated by Django 4.2.27 on 2025-12-31 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='clients_source__9ad47c_idx',
        ),
        migrations.RemoveField(
            model_name='client',
            name='source_channel',
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='core.subsource'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['source'], name='clients_source__194b59_idx'),
        ),
    ]
