# Generated by Django 4.2.27 on 2025-12-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_change_client_source_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='fixed_period_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='rate_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='rate_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
