# Generated by Django 4.2.27 on 2025-12-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_case_bank_name_case_fixed_period_years_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankform',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bankform',
            name='type',
            field=models.CharField(choices=[('accountOpeningForm', 'Account Opening Form'), ('fts', 'FTS'), ('kfs', 'KFS'), ('undertakings', 'Undertakings'), ('bankChecklist', 'Bank Checklist'), ('other', 'Other Document')], max_length=30),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('passport', 'Passport'), ('emiratesId', 'Emirates ID'), ('visa', 'Visa'), ('salaryCertificate', 'Salary Certificate'), ('payslips', 'Payslips'), ('bankStatements', 'Bank Statements'), ('creditCardStatement', 'Credit Card Statement'), ('loanStatements', 'Loan Statements'), ('other', 'Other Document')], max_length=30),
        ),
    ]
