# Generated by Django 4.2.27 on 2025-12-31 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_document_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='core.client')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='core.lead')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['lead'], name='whatsapp_me_lead_id_b60d7d_idx'), models.Index(fields=['client'], name='whatsapp_me_client__d809c9_idx'), models.Index(fields=['phone'], name='whatsapp_me_phone_439d41_idx')],
            },
        ),
    ]
