# Generated by Django 4.2.27 on 2026-01-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_whatsappmessage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_channel_3d83b7_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='channel',
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.subsource'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source'], name='leads_source__1d615d_idx'),
        ),
    ]
