# Generated by Django 4.2.27 on 2026-01-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_lead_leads_channel_3d83b7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatuschange',
            name='type',
            field=models.CharField(choices=[('converted_from_lead', 'Converted from Lead'), ('converted_to_case', 'Converted to Case'), ('not_eligible', 'Not Eligible'), ('not_proceeding', 'Not Proceeding')], max_length=30),
        ),
    ]
